// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimCap.DAO;

namespace TimCap.Migrations
{
    [DbContext(typeof(TimeCapContext))]
    [Migration("20210515063310_foreign1")]
    partial class foreign1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("TimCap.Model.Cap", b =>
                {
                    b.Property<int>("CapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Story")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("CapId");

                    b.ToTable("Caps");
                });

            modelBuilder.Entity("TimCap.Model.OutTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("OTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OutId");

                    b.ToTable("Outs");
                });

            modelBuilder.Entity("TimCap.Model.OutTime", b =>
                {
                    b.HasOne("TimCap.Model.Cap", "Cap")
                        .WithMany()
                        .HasForeignKey("OutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cap");
                });
#pragma warning restore 612, 618
        }
    }
}
